import game1 from "../images/game2.jpg";

export const tournament = {
  id: 1,
  img: game1,
  title: "Dota 2 tournament",
  date: "12.12.2003 | 17:00",
  inf: "5v5 | 32 места | 1.000.000₽ ",
  prize_fund: 100000,
  team: true,
  description:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, odit.",
  manager: { id: 0, avatar: "/src/images/game1.jpg", name: "gg" },
  contact: "@iburdik",
  status: "open",
  has_groupstage: true,
  group_stage: {
    id: 123,
    groups: [
      {
        id: 124,
        letter: "A",
        matches: [
          {
            id: 1,
            number: 1,
            format: "bo3",
            status: "upcoming",
            participant1: {
              id: 120,
              name: "Vasya",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Petya",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 3,
            maps: [
              { id: 123, external_url: "/test_url", winner_id: "121" },
              { id: 124, external_url: "/test_url", winner_id: "120" },
              { id: 125, external_url: "/test_url", winner_id: "120" },
            ],
          },
          {
            id: 2,
            number: 1,
            format: "bo1",
            status: "ongoing",
            participant1: {
              id: 120,
              name: "Vasya",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Arseny",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 1,
          },
          {
            id: 3,
            number: 3,
            format: "bo1",
            status: "completed",
            participant1: {
              id: 120,
              name: "Vasya",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Arseny",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 1,
          },
        ],
        group_rows: [
          {
            id: 333,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom1" },
            user: null,
          },
          {
            id: 334,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom2" },
            user: null,
          },
          {
            id: 334,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom2" },
            user: null,
          },
          {
            id: 334,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom2" },
            user: null,
          },
          {
            id: 334,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom2" },
            user: null,
          },
          {
            id: 335,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom3" },
            user: null,
          },
        ],
      },
      {
        id: 124,
        letter: "A",
        matches: [
          {
            id: 1,
            number: 1,
            format: "bo1",
            status: "upcoming",
            participant1: {
              id: 120,
              name: "Vasya",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Petya",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 3,
          },
          {
            id: 2,
            number: 1,
            format: "bo1",
            status: "ongoing",
            participant1: {
              id: 120,
              name: "Vasya",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Arseny",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 1,
          },
          {
            id: 3,
            number: 3,
            format: "bo1",
            status: "completed",
            participant1: {
              id: 120,
              name: "Vasya",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Arseny",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 1,
          },
        ],
        group_rows: [
          {
            id: 333,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom1" },
            user: null,
          },
          {
            id: 334,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom2" },
            user: null,
          },
          {
            id: 334,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom2" },
            user: null,
          },
          {
            id: 334,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom2" },
            user: null,
          },
          {
            id: 334,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom2" },
            user: null,
          },
          {
            id: 335,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            team: { id: 0, avatar: "/src/images/game1.jpg", name: "kom3" },
            user: null,
          },
        ],
      },

      {
        id: 125,
        letter: "B",
        matches: [
          {
            id: 1,
            number: 5,
            format: "bo1",
            status: "upcoming",
            participant1: {
              id: 120,
              name: "Inna",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Arseny",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 1,
          },
          {
            id: 1,
            number: 5,
            format: "bo1",
            status: "upcoming",
            participant1: {
              id: 120,
              name: "Inna",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Arseny",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 1,
          },
          {
            id: 1,
            number: 5,
            format: "bo1",
            status: "upcoming",
            participant1: {
              id: 120,
              name: "Inna",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Arseny",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 1,
          },
          {
            id: 1,
            number: 5,
            format: "bo1",
            status: "upcoming",
            participant1: {
              id: 120,
              name: "Inna",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Arseny",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 1,
          },
          {
            id: 2,
            number: 6,
            format: "bo1",
            status: "upcoming",
            participant1: {
              id: 120,
              name: "Inna",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Petya",
              avatar: "/src/images/game1.jpg",
            },
            score1: 2,
            score2: 1,
          },
        ],
        group_rows: [
          {
            id: 333,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            user: { id: 0, avatar: "/src/images/game1.jpg", name: "inna" },
            team: null,
          },
          {
            id: 333,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            user: { id: 0, avatar: "/src/images/game1.jpg", name: "inna" },
            team: null,
          },
          {
            id: 333,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            user: { id: 0, avatar: "/src/images/game1.jpg", name: "inna" },
            team: null,
          },
          {
            id: 334,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            user: { id: 0, avatar: "/src/images/game1.jpg", name: "kira" },
            team: null,
          },
          {
            id: 335,
            place: 1,
            wins: 2,
            draws: 1,
            loses: 0,
            user: { id: 0, avatar: "/src/images/game1.jpg", name: "nika" },
            team: null,
          },
        ],
      },
    ],
  },

  playoff_stage: {
    id: 123,

    rounds: [
      {
        letter: "1",
        matches: [
          {
            id: "uuid-1-1",
            number: 1,
            bracket: "W",
            format: "bo3",
            status: "ongoing",
            participant1: {
              id: 120,
              name: "Igor",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Petya",
              avatar: "/src/images/game1.jpg",
            },
            score1: 0,
            score2: 1,
            depends_on_match_1_id: null,
            depends_on_match_2_id: null,
            winner_to_match_id: "uuid-2-1",
            maps: [
              { id: 997 },
              { id: 998 },
              { id: 999 },
            ],
          },
          {
            id: "uuid-1-2",
            number: 2,
            bracket: "W",
            format: "bo1",
            status: "ongoing",
            participant1: {
              id: 120,
              name: "Jeka",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Arseny",
              avatar: "/src/images/game1.jpg",
            },
            score1: 1,
            score2: 0,
            depends_on_match_1_id: null,
            depends_on_match_2_id: null,
            winner_to_match_id: "uuid-2-1",
          },
          {
            id: "uuid-1-3",
            number: 3,
            bracket: "W",
            format: "bo1",
            status: "completed",
            participant1: {
              id: 120,
              name: "Inna",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Igor",
              avatar: "/src/images/game1.jpg",
            },
            score1: 0,
            score2: 1,
            depends_on_match_1_id: null,
            depends_on_match_2_id: null,
            winner_to_match_id: "uuid-2-2",
          },
          {
            id: "uuid-1-4",
            number: 4,
            bracket: "W",
            format: "bo1",
            status: "completed",
            participant1: {
              id: 120,
              name: "Jopich",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Popich",
              avatar: "/src/images/game1.jpg",
            },
            score1: 0,
            score2: 1,
            depends_on_match_1_id: null,
            depends_on_match_2_id: null,
            winner_to_match_id: "uuid-2-2",
          },
        ],
      },
      {
        id: 125,
        letter: "2",
        matches: [
          {
            id: "uuid-2-1",
            number: 5,
            bracket: "W",
            format: "bo1",
            status: "upcoming",
            participant1: {
              id: 120,
              name: "Petya",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Jeka",
              avatar: "/src/images/game1.jpg",
            },
            score1: 0,
            score2: 1,
            depends_on_match_1_id: "uuid-1-1",
            depends_on_match_2_id: "uuid-1-2",
            winner_to_match_id: "uuid-final-1",
          },
          {
            id: "uuid-2-2",
            number: 6,
            bracket: "W",
            format: "bo1",
            status: "upcoming",
            participant1: {
              id: 120,
              name: "Igor",
              avatar: "/src/images/game1.jpg",
            },
            participant2: {
              id: 121,
              name: "Popich",
              avatar: "/src/images/game1.jpg",
            },
            score1: 0,
            score2: 1,
            depends_on_match_1_id: "uuid-1-3",
            depends_on_match_2_id: "uuid-1-4",
            winner_to_match_id: "uuid-final-1",
          },
        ],
      },
    ],
  },

  final: {
    id: "uuid-final-1",
    number: 7,
    bracket: "W",
    format: "bo3",
    status: "upcoming",
    participant1: {
      id: 120,
      name: "Jeka",
      avatar: "/src/images/game1.jpg",
    },
    participant2: {
      id: 121,
      name: "Popich",
      avatar: "/src/images/game1.jpg",
    },
    score1: 2,
    score2: 1,
  },

  participants: [
    { id: 0, avatar: "/src/images/game1.jpg", name: "gg" },
    { id: 1, avatar: "/src/images/game1.jpg", name: "Оля" },
    { id: 1, avatar: "/src/images/game1.jpg", name: "Оля" },
    { id: 1, avatar: "/src/images/game1.jpg", name: "Оля" },
  ],
};
